### ISSUE TITLE
Coordinated effort

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/joss-36#1]
I suggest coordinating volunteers willing to type in pages.  The listing is here: https://github.com/PDP-10/joss-36/blob/master/doc/RM5437.pdf

The listing starts with "PAGE 1", which is page 3 in the document, or page 21 in the PDF.  I suggest using the *listing* page numbering, which goes to 132.  If you want to type in some pages, check the boxes here:

- [x] PAGE 1
- [x] PAGE 2
- [x] PAGE 3
- [x] PAGE 4
- [x] PAGE 5
- [x] PAGE 6
- [x] PAGE 7
- [x] PAGE 8
- [x] PAGE 9
- [x] PAGE 10
- [x] PAGE 11
- [x] PAGE 12
- [x] PAGE 13
- [x] PAGE 14
- [x] PAGE 15
- [x] PAGE 16
- [x] PAGE 17
- [x] PAGE 18
- [x] PAGE 19
- [x] PAGE 20
- [x] PAGE 21
- [x] PAGE 22
- [x] PAGE 23
- [x] PAGE 24
- [x] PAGE 25
- [x] PAGE 26
- [x] PAGE 27
- [x] PAGE 28
- [x] PAGE 29
- [x] PAGE 30
- [x] PAGE 31
- [x] PAGE 32
- [x] PAGE 33
- [x] PAGE 34
- [x] PAGE 35
- [x] PAGE 36
- [x] PAGE 37
- [x] PAGE 38
- [x] PAGE 39
- [x] PAGE 40
- [x] PAGE 41
- [x] PAGE 42
- [x] PAGE 43
- [x] PAGE 44
- [x] PAGE 45
- [x] PAGE 46
- [x] PAGE 47
- [x] PAGE 48
- [x] PAGE 49
- [x] PAGE 50
- [x] PAGE 51
- [x] PAGE 52
- [x] PAGE 53
- [x] PAGE 54
- [x] PAGE 55
- [x] PAGE 56
- [x] PAGE 57
- [x] PAGE 58
- [x] PAGE 59
- [x] PAGE 60
- [x] PAGE 61
- [x] PAGE 62
- [x] PAGE 63
- [x] PAGE 64
- [x] PAGE 65
- [x] PAGE 66
- [x] PAGE 67
- [x] PAGE 68
- [x] PAGE 69
- [x] PAGE 70
- [x] PAGE 71
- [x] PAGE 72
- [x] PAGE 73
- [x] PAGE 74
- [x] PAGE 75
- [x] PAGE 76
- [x] PAGE 77
- [x] PAGE 78
- [x] PAGE 79
- [x] PAGE 80
- [x] PAGE 81
- [x] PAGE 82
- [x] PAGE 83
- [x] PAGE 84
- [x] PAGE 85
- [x] PAGE 86
- [x] PAGE 87
- [x] PAGE 88
- [x] PAGE 89
- [x] PAGE 90
- [x] PAGE 91
- [x] PAGE 92
- [x] PAGE 93
- [x] PAGE 94
- [x] PAGE 95
- [x] PAGE 96
- [x] PAGE 97
- [x] PAGE 98
- [x] PAGE 99
- [x] PAGE 100
- [x] PAGE 101
- [x] PAGE 102
- [x] PAGE 103
- [x] PAGE 104
- [x] PAGE 105
- [x] PAGE 106
- [x] PAGE 107
- [x] PAGE 108
- [x] PAGE 109
- [x] PAGE 110
- [x] PAGE 111
- [x] PAGE 112
- [x] PAGE 113
- [x] PAGE 114
- [x] PAGE 115
- [x] PAGE 116
- [x] PAGE 117
- [x] PAGE 118
- [x] PAGE 119
- [x] PAGE 120
- [x] PAGE 121
- [x] PAGE 122
- [x] PAGE 123
- [x] PAGE 124
- [x] PAGE 125
- [x] PAGE 126
- [x] PAGE 127
- [x] PAGE 128
- [x] PAGE 129
- [x] PAGE 130
- [x] PAGE 131
- [x] PAGE 132

**Comment by larsbrinkhoff** [comment]
Thank you Emacs Lisp for automating the list.

**Comment by PashPaw** [comment]
I just finished page 9.  Working on Page 10 now.  I will likely go back to the first section and go through and check and add some comments about what page and the title according to the listing.  This should make it easier to debug if needed.

**Comment by PashPaw** [comment]
I also agree with using the listing page numbering.  It's what I've been personally using.  I also would like to suggest using the titles in listing so we can figure out where we're at more easily.  The josxxx.mac naming scheme is for the section we're at.

**Comment by dabridgham** [comment]
I went with the name page033-037.mac.  It not only tells you the page range so you can look for gaps but it should end up that you can just cat all the page*.mac files together to get a combined file in the right order.

**Comment by dabridgham** [comment]
Where's the right place to put notes about either interesting things we discover or likely problems with the code.  And example of the latter is on page 43, the BELF constant.  I've decoded the octal dump to see that the ASCII is supposed to be BEL, CR, EOT, 0, 0 but I don't know how to write that so macro-10 will generate the right output.  This ought to be flagged somehow so whoever tries to build the code can go have a look.

An example of the former is on page 40, the line:
`cono 500,1;  pulse the "joss here" flop`
So I'm thinking they added some custom I/O device at I/O location 500.  Maybe something wants to be added to the PDP-6 simulator.

**Comment by PashPaw** [comment]
The Wiki probably.  We know that a [Strowger switch](https://en.wikipedia.org/wiki/Strowger_switch) could be attached to external ASR-33s.

My favorite so far is the "BLAST OFF SWITCH".  I really want to know what that *is*

**Comment by larsbrinkhoff** [comment]
My only observation is the use of `TSX` as an macro for `PUSHJ P,`.  This mnemonic seems to be used in CTSS too.

**Comment by larsbrinkhoff** [comment]
I think maybe the source code had subtitles and page dividers.  The second line of each page seems to have a subtitle.  MACRO-10 has the pseudo-op SUBTTL.  ^L is used to break pages.

**Comment by larsbrinkhoff** [comment]
Another blast off sighting on page 106.  There's a subroutine call to
BOFF.

**Comment by larsbrinkhoff** [comment]
It looks to me the Type 270 disk driver code is in a separate file we don't have.  Fortunately it's described well in RM5257 so it can be implemented.  It's described as essentially a co-routine.

**Comment by dabridgham** [comment]
PashPaw, I just read that Introduction document and now I see what the Strowger switch is for.  Neat.

**Comment by PashPaw** [comment]
Page 109 seems to start the interpreter.

**Comment by dabridgham** [comment]
I have a MACRO-6 question.  There seem to be a bunch of lines that start with a comma.  They look like comment lines and I've been assuming that was a misprint.  In many cases, it's awfully clear it's a comma though and not a semi-colon.  So are comments starting with a comma a thing in MACRO-6?

**Comment by larsbrinkhoff** [comment]
@aap says:
> superfluous operands are ignored so you can use comma for comments

**Comment by larsbrinkhoff** [comment]
Doesn't seem to work with a 1979 MACRO-10.

**Comment by larsbrinkhoff** [comment]
FYI @philbudne, we are trying to rebuild PDP-6 JOSS-II from a program listing.

**Comment by larsbrinkhoff** [comment]
All, be careful with the macros and opdefs.  The listing includes both the macro/opdef invokation and the expansion.  The source file should only have the invokation.

Example from listing:
```
DISPLAY:TSX     CMESS
        TSX     MR0;            SEND ERROR NUMBER
        TSX     CMESS
        XMT ^D13,M100;        AC TITLE
OPDEF X[^D13B12]
X M100
```

Source should only have
```
DISPLAY:TSX     CMESS
        TSX     MR0;            SEND ERROR NUMBER
        TSX     CMESS
        XMT ^D13,M100;        AC TITLE
OPDEF X[^D13B12]
X M100
```

**Comment by larsbrinkhoff** [comment]
Another example.  Listing, page 96:

```
                         30490     dof:    fsw a;      get the switches
006664  200000 006364'       move a,switch
```

Note how the first line has line number (30490) but no address or data.  The second line has address and data, but no line number.  Source should be just the first line.

**Comment by PashPaw** [comment]
I was only commenting on them and keeping them in as bookmarks.  I figured they were expansions.

**Comment by larsbrinkhoff** [comment]
I submitted a pull request to remove the expansions, but I can make them
comments if you prefer.

**Comment by PashPaw** [comment]
It doesn't matter to me.  My rationale is that it provided useful feedback on how it should behave.

**Comment by PashPaw** [comment]
WOOOOOO!  Thanks!

**Comment by larsbrinkhoff** [comment]
Typing finished; closing.

**Comment by larsbrinkhoff** [comment]
I hope to see you all for some SHRDLU typing soon!
