### ISSUE TITLE
Attempting to assemble

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/joss-36#29]
Random notes and comments about assembling the code.

**Comment by larsbrinkhoff** [comment]
First try, josinit.mac.  I'm not sure what all this means.  `U` is undefined?  `+D` should be `^D`

```
PAGE 1
O       000007' 000 01 0 00 000121              MODEM   B,SAVE+1
R       000050' 200 16 0 00 000567'             MOVE    S,[XWD -+D20,IOA-1];  DATA CONTROL WORD
U       000346' 003 02 0 00 000000*     X M101
U                       000000          OPDEF X[+D50B12]
UE      000347' 000 00 0 00 000000      X M101
UE      000404' 000000  642634*         M101    ASCII   ?OFFENDING LOCATION (11):  CONTENTS(@11): @17: @0:?

D50B12  UNASSIGNED, DEFINED AS IF EXTERNAL
M101    UNASSIGNED, DEFINED AS IF EXTERNAL
MODEM   UNASSIGNED, DEFINED AS IF EXTERNAL
?8 ERRORS DETECTED

PROGRAM BREAK IS 000577
CPU TIME USED 00:00.245

3K CORE USED
```

**Comment by larsbrinkhoff** [comment]
OPDEF expansions should be removed.  `MODEM` should be `MOVEM`.

**Comment by larsbrinkhoff** [comment]
`M101` is missing a `:`.  Now assembling OK.

**Comment by larsbrinkhoff** [comment]
Here's what my MACRO version says about the supervisor files:

```
?MCRNES NO END STATEMENT ENCOUNTERED ON INPUT FILE
IN DEFINE ON PAGE 1 AT PATCH + 201
PAGE 1
N       000020' 000000  000000          ^L
N       000021' 000000  000000          ^L
N       000022' 000000  000000          ^L
N       000023' 000000  000000          ^L

?MCRNES NO END STATEMENT ENCOUNTERED ON INPUT FILE
IN DEFINE ON PAGE 1 AT PATCH + 199

?5 ERRORS DETECTED

PROGRAM BREAK IS 000024
```

**Comment by larsbrinkhoff** [comment]
The listing have the program break at 010604.

**Comment by PashPaw** [comment]
Noted.  See: https://gist.github.com/PashPaw/43c9ad67fddabeef6bc5531c830839dd/revisions for MACRO V47's listing.

**Comment by larsbrinkhoff** [comment]
The macro body for XMT is missing a line: `X A>`

**Comment by larsbrinkhoff** [comment]
Now I get lots of errors, which is more reasonable.  Just the first few:

```
T10.     +4     PAGE 1
M                                        T10.:
SCP2     +8     M                                       SCP2:    POINT 4-S.QUE
SCP3     +1     M                                       SCP3:    POINT 7-S.QUE
SCP4     +1     M                                       SCP4:    POINT 6-S.QUE
SC9      +1     M                                       SC9:     NOP   0-S.QUE
CT35     +2     M                                       CT10:   Z;             !
                            MINUTE
CT35     +3     M                                       CT10A:  Z;             !
                            HOUR
CT48C    +32    M                                       CT48B:  Z;
CT48C    +33    M                                       CT48C:  Z;
SS18     +11    PAGE 46
M       SS10:   BYTE    (5) QP.S,ABG.S,DSU.S,GR.S,DQ.S,CK.S,DIP.S,DCT.S,END.S
SS18     +13    M       SS11:   BYTE    (5) QP.S,ABG.S,DSU.S,GR.S,END.S
PAGE 1
N       000020' 000000  000000          ^L
N       000021' 000000  000000          ^L
N       000022' 000000  000000          ^L
N       000023' 000000  000000          ^L
N       000024' 000000  000000          ^L
N       000025' 000000  000000                                  ^L
```

**Comment by PashPaw** [comment]
Right.  Can you give me a general idea where XMT A is?

**Comment by larsbrinkhoff** [comment]
On page 5, the definition of XMT should look like this:

```
        DEFINE XMT (M,A); TRANSMIT M CHARACTERS FROM A
<OPDEF X[M'B12]
X A>
```

**Comment by PashPaw** [comment]
Thank you!

**Comment by larsbrinkhoff** [comment]
I think I need a crash course in MACRO error messages.

- N - supress something?
- U - Undefined symbol.
- M - Multiple symbol definition.

**Comment by PashPaw** [comment]
Yup.  I uploaded the MACRO-10 document from 1972 to help clarify things.

**Comment by larsbrinkhoff** [comment]
Assembler errors now start around page 35, so at roughly 25%.  And this is the easy part because typos are flagged.  The unflagged errors will be harder to find.

**Comment by PashPaw** [comment]
As expected.  But, this is massive and it may take awhile for us to fully debug it.

**Comment by larsbrinkhoff** [comment]
Possible bug.  `IN99: AOS CT27` but CT27 isn't defined.

**Comment by larsbrinkhoff** [comment]
Fixed all assembler errors except CT27.

**Comment by dabridgham** [comment]
CT27 is defined on page 14.  For some reason, it's between CT15 and CT16.  I'm sure that odd placement lead to its being missed.

**Comment by larsbrinkhoff** [comment]
Thanks, I'll add it to #32.

**Comment by PashPaw** [comment]
I'm only getting one error now (in reality, this pops up at pg. 126 in the listing):
`PAGE 128
Q       010306' 554 01 0 00 000016      PUTB5:  HLRZ    B,S,BUF(S);     P
OINTER TO LAST BUFFER`

I'll double check to see what's going on here.

**Comment by PashPaw** [comment]
Ah.  I see.  Fixed.  S,BUF is is supposed to be S.BUF.

**Comment by PashPaw** [comment]
```

.ex jossu,josini
LOADING

000045 UNDEFINED GLOBALS

INITIA    010326
C28       006731
SEQ       007733
C25       011367
CONSOL    005674
DISC.S    007421
DISC.D    005016
DISC.C    006161
SHUT      006256
USIZE     010341
DDT       011373
FILE      005005
RISIG     007561
RESULT    006166
DBUF      010525
T80.99    007374
T80       007370
PROG      005021
COMTIM    010331
PAGNO     010351
ONTIME    010315
C26       011371
C20       011505
D.TIME    004126
ACTION    006160
C32       004225
C31       006415
C30       004160
KEY       005007
JOBNO     010007
C27       010462
INTENT    010303
SPARE4    007576
SPARE3    010355
SPARE2    010353
SPARE1    010327
INTBEG    007716
?

LOADER 5K CORE
?EXECUTION DELETED

EXIT
.
```

That's progress...to some degree.

**Comment by PashPaw** [comment]
Page 44 has very specific assembly instructions:

`;		NOTE THAT PROPER RECOVERY FROM MACHINE ERRORS
;		DEPENDS, IN PART, ON A SPECIFIC LOADING ORDER
;		FOR JOSS COMPONENTS.  IN PARTICULAR, THE ORDER
;		SHOULD BE: ARITH,DISTRIB, DISC, SU, CPU, DDT, IU.`

**Comment by larsbrinkhoff** [comment]
Very good!  Clearly spells out the components and their names.

**Comment by PashPaw** [comment]
Yup!  It looks like RAND does keep a version of cpu.mac in their archives but it’s only available on request.

**Comment by larsbrinkhoff** [comment]
What, where?  And what is CPU?  I recognize all of the others.

**Comment by PashPaw** [comment]
"The material is presented in a narrative form, augmented by flow-chart representations of most of the principal routines, _and is in part designed to serve as prolegomena to the annotated machine-language listings of the routines (copies of which are obtainable from RAND)_."

https://www.rand.org/pubs/research_memoranda/RM5270.html

**Comment by larsbrinkhoff** [comment]
I'll ask the archivist about those listings.

**Comment by PashPaw** [comment]
Thanks.  I wonder if there’s more?  Now I’m feeling a little more optimistic. I would like to see an OS running on the PDP-6 sims.

Granted, this will be a big, giant time-shared interpreter like ACCESS BASIC, TSS/8,  and early versions of RSTS were but it’s better than nothing.

**Comment by larsbrinkhoff** [comment]
I think this can be closed now.
